'use client';

import './globals.css'
// import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Navbar } from 'flowbite-react';

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar
          fluid
          rounded
        >
          <Navbar.Brand
            href="https://toolmate.co.in"
          >
            <img
              alt="ToolMate Logo"
              className="mr-3 h-6 sm:h-9"
              src="https://toolmate.co.in/assets/logo/ToolmateLight.png"
            />
            <span className="self-center whitespace-nowrap text-xl font-semibold dark:text-white">
              ToolMate
            </span>
          </Navbar.Brand>
          <Navbar.Toggle />
          <Navbar.Collapse>
            <Navbar.Link
              active
              href="#"
            >
              <p>
                Home
              </p>
            </Navbar.Link>
            <Navbar.Link
              href="#"
            >
              <p>
                About
              </p>
            </Navbar.Link>
            <Navbar.Link href="#">
              Services
            </Navbar.Link>
            <Navbar.Link href="#">
              Pricing
            </Navbar.Link>
            <Navbar.Link href="#">
              Contact
            </Navbar.Link>
          </Navbar.Collapse>
        </Navbar>
        {children}
      </body>
    </html>
  )
}
